# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='quantity_sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='products',
            field=models.ManyToManyField(
                null=True, through='inventory.InvoiceDetail', to='inventory.Products'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='remaining',
            field=models.DecimalField(
                decimal_places=2, max_digits=9, null=True),
        ),
    ]
