# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170703_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, default=400, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='products',
            field=models.ManyToManyField(
                through='inventory.InvoiceDetail', to='inventory.Products'),
        ),
    ]
