# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170706_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), (
                'Partial', 'Partial')], default='Open', max_length=100),
        ),
    ]
