# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170706_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, max_digits=9, null=True),
        ),
    ]
