# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-09 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_payments_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='remaining',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9),
        ),
    ]
