# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-20 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_payments_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=100),
        ),
    ]
