# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
