# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20170619_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
