# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170620_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='id',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_number',
            field=models.CharField(default='1', max_length=100, primary_key=True, serialize=False),
        ),
    ]
